from typing import TextIO
import numpy as np
import numpy.typing as npt

from slaterform.analysis import grid as grid_mod
from slaterform.structure import molecule


def write_cube_data(
    mol: molecule.Molecule,
    grid: grid_mod.RegularGrid,
    data: npt.NDArray[np.float64],
    description: str,
    f: TextIO,
) -> None:
    """Writes volumetric data in a Gaussian Cube format.

    Args:
        mol: The molecule associated with the data.
        grid: The regular grid defining the volumetric data.
        data: The volumetric data to write, shape grid.dims.
        description: A description string for the cube file.
        f: The file-like object to write the cube data to.
    """
    if data.shape != grid.dims:
        raise ValueError(
            f"Data shape {data.shape} does not match grid dimensions {grid.dims}"
        )

    n_atoms = len(mol.atoms)

    # Header
    f.write("Generated by Slaterform\n")
    f.write(f"{description}\n")

    # Origin line (includes n_atoms)
    # Format: N_atoms, OriginX, OriginY, OriginZ
    f.write(
        f"{n_atoms:5d} {grid.origin[0]:12.6f} {grid.origin[1]:12.6f} {grid.origin[2]:12.6f}\n"
    )

    # Voxel vectors (Defines the axes)
    f.write(f"{grid.dims[0]:5d} {grid.spacing:12.6f} {0.0:12.6f} {0.0:12.6f}\n")
    f.write(f"{grid.dims[1]:5d} {0.0:12.6f} {grid.spacing:12.6f} {0.0:12.6f}\n")
    f.write(f"{grid.dims[2]:5d} {0.0:12.6f} {0.0:12.6f} {grid.spacing:12.6f}\n")

    # Atom list
    # Format: AtomicNumber, Charge, X, Y, Z
    for atom in mol.atoms:
        f.write(
            f"{atom.number:5d} {float(atom.number):12.6f} "
            f"{atom.position[0]:12.6f} {atom.position[1]:12.6f} {atom.position[2]:12.6f}\n"
        )

    # Volumetric Data
    data = data.flatten()

    # Write in blocks of 6 scientific notation floats
    for i, val in enumerate(data):
        f.write(f"{val:13.5E}")
        if (i + 1) % 6 == 0:
            f.write("\n")

    # Final newline if not aligned
    if len(data) % 6 != 0:
        f.write("\n")
