import numpy as np
import numpy.typing as npt

from slaterform.analysis import grid as grid_mod
from slaterform.structure import molecule


def generate_cube_data(
    mol: molecule.Molecule,
    grid: grid_mod.RegularGrid,
    data: npt.NDArray[np.float64],
    description: str,
) -> str:
    """Writes volumetric data to a Gaussian Cube format.

    Args:
        mol: The molecule associated with the data.
        grid: The regular grid defining the volumetric data.
        data: The volumetric data to write, shape grid.dims.
        description: A description string for the cube file.
    """
    if data.shape != grid.dims:
        raise ValueError(
            f"Data shape {data.shape} does not match grid dimensions {grid.dims}"
        )

    n_atoms = len(mol.atoms)
    buffer: list[str] = []

    # Header
    buffer.append("Generated by Slaterform\n")
    buffer.append(f"{description}\n")

    # Origin line (includes n_atoms)
    # Format: N_atoms, OriginX, OriginY, OriginZ
    buffer.append(
        f"{n_atoms:5d} {grid.origin[0]:12.6f} {grid.origin[1]:12.6f} {grid.origin[2]:12.6f}\n"
    )

    # Voxel vectors (Defines the axes)
    buffer.append(f"{grid.dims[0]:5d} {grid.spacing:12.6f} 0.000000 0.000000\n")
    buffer.append(f"{grid.dims[1]:5d} 0.000000 {grid.spacing:12.6f} 0.000000\n")
    buffer.append(f"{grid.dims[2]:5d} 0.000000 0.000000 {grid.spacing:12.6f}\n")

    # Atom list
    # Format: AtomicNumber, Charge, X, Y, Z
    for atom in mol.atoms:
        buffer.append(
            f"{atom.number:5d} {float(atom.number):12.6f} "
            f"{atom.position[0]:12.6f} {atom.position[1]:12.6f} {atom.position[2]:12.6f}\n"
        )

    # Volumetric Data
    data = data.flatten()

    # Write in blocks of 6 scientific notation floats
    for i, val in enumerate(data):
        buffer.append(f"{val:13.5E}")
        if (i + 1) % 6 == 0:
            buffer.append("\n")

    # Final newline if not aligned
    if len(data) % 6 != 0:
        buffer.append("\n")

    return "".join(buffer)
