import dataclasses
from io import StringIO
import pytest

import numpy as np
import numpy.typing as npt

from slaterform.analysis import grid as analysis_grid
from slaterform.analysis import cube_io
from slaterform.structure import molecule
from slaterform.structure import atom

_MOLECULE = molecule.Molecule(
    atoms=[
        atom.Atom(symbol="H", number=1, position=np.array([1.0, 0.0, 0.0])),
        atom.Atom(symbol="O", number=8, position=np.array([0.0, 1.0, 0.0])),
    ]
)

_GRID = analysis_grid.RegularGrid(
    origin=np.array([-1.0, -2.0, -3.0]),
    spacing=0.5,
    dims=(2, 2, 2),
)

_DATA = np.array(
    [
        [[0.1, 0.2], [0.3, 0.4]],
        [[0.5, 0.6], [0.7, 0.8]],
    ],
    dtype=np.float64,
)

_DESCRIPTION = "orbital density"

_CUBE_DATA = """Generated by Slaterform
orbital density
    2    -1.000000    -2.000000    -3.000000
    2     0.500000     0.000000     0.000000
    2     0.000000     0.500000     0.000000
    2     0.000000     0.000000     0.500000
    1     1.000000     1.000000     0.000000     0.000000
    8     8.000000     0.000000     1.000000     0.000000
  1.00000E-01  2.00000E-01  3.00000E-01  4.00000E-01  5.00000E-01  6.00000E-01
  7.00000E-01  8.00000E-01
"""


def test_write_cube_data(
    mol: molecule.Molecule = _MOLECULE,
    grid: analysis_grid.RegularGrid = _GRID,
    data: npt.NDArray[np.float64] = _DATA,
    description: str = _DESCRIPTION,
    expected_cube_data: str = _CUBE_DATA,
) -> None:
    f = StringIO()
    cube_io.write_cube_data(
        mol=mol, grid=grid, data=data, description=description, f=f
    )

    output = f.getvalue()
    print(output)
    assert output == _CUBE_DATA
